/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

import opaTest from "sap/ui/test/opaQunit";
import type { Given, When, Then } from "./types/OpaJourneyTypes";
import type { FilterFieldIdentifier } from "sap/fe/test/api/FilterBarAPI";
import runner from "./pages/JourneyRunner";

function journey() {
    QUnit.module("ProductsSetListListReport journey");

    opaTest("Start application", function (Given: Given, _When: When, Then: Then) {
        Given.iStartMyApp();

        Then.onTheProductsSetListGenerated.iSeeThisPage();
    });

    opaTest("Check filter bar", function (_Given: Given, _When: When, Then: Then) {
        Then.onTheProductsSetListGenerated.onFilterBar().iCheckFilterField("Currency" as unknown as FilterFieldIdentifier);
    });

    // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
    // opaTest("Perform a global search and check the result", function (Given: Given, When: When, Then: Then) {
    //     When.onTheProductsSetListGenerated.onFilterBar().iChangeSearchField("Search Term");
    //     When.onTheProductsSetListGenerated.onFilterBar().iExecuteSearch();
    //     Then.onTheProductsSetListGenerated.onTable("").iCheckRows();
    // });

    opaTest("Check table columns and actions", function (_Given: Given, _When: When, Then: Then) {
        Then.onTheProductsSetListGenerated.onTable("").iCheckColumns(undefined, {"product":{"header":"Product ID"},"productName":{"header":"Product Name"},"description":{"header":"Description"},"price":{"header":"Price"}});

    });



    opaTest("Navigate to ObjectPage", function (_Given: Given, When: When, Then: Then) {
        // Note: this test will fail if the ListReport page doesn't show any data
        
        When.onTheProductsSetListGenerated.onFilterBar().iExecuteSearch();
        
        Then.onTheProductsSetListGenerated.onTable("").iCheckRows();

        When.onTheProductsSetListGenerated.onTable("").iPressRow(0);
        Then.onTheProductsSetObjectPageGenerated.iSeeThisPage();

    });

    opaTest("Teardown", function (Given: Given) {
        // Cleanup
        Given.iTearDownMyApp();
    });
}

runner.run([journey]);
